#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2022-2026 Mark Makies
###############################################################################
# PIMD Pack State of Charge (pimd_pack.py) v1
# — shared 6S pack fuel-gauge maths: loaded pack millivolts -> state of charge
#   percent, plus a live discharge-rate tracker that projects time remaining.
# Runs on Ubuntu desktop / laptop, pure stdlib (no GUI, no Qt, no NumPy).
#
# Deliberately standalone, like pimd_shape.py: pimd_gui.py, pimd_classviz.py,
# pimd_delaycal.py and pimd_rawlog.py all import it so the four apps can never
# disagree about the same pack. This REPLACES the per-app copies that used to
# live in each file -- those carried a "every PC app stands alone" note, and
# that decision was deliberately reversed here, because four hand-synced copies
# of a calibration table is exactly the thing that drifts.
#
# WHY NOT A PER-CELL OCV CURVE
# ----------------------------
# The previous implementation divided pack millivolts by six and read a
# resting Samsung ICR18650-26C open-circuit curve. That is wrong twice over:
#   * it is a RESTING curve handed a LOADED terminal voltage, and
#   * pack/6 assumes a balanced string.
# On 2026-08-12 the then-fitted pack was bench-confirmed badly imbalanced (four
# cells at 3.84 V, two weak cells near 2.83 V), so pack/6 described nothing
# physical and the gauge read 11 % against a charger's 53 %. A balanced pack
# fixes the second problem but not the first, and the OCV route stays fragile
# where it matters: pack/6 lands on the steep part of the Li-ion curve, so a
# 400 mV change in the assumed sag moves the reading at 22.0 V from 23 % to
# 36 %. It needs a sag constant nobody has measured on the pack in the rig.
#
# WHAT THIS DOES INSTEAD
# ----------------------
# State of charge is the fraction of usable PULSING RUNTIME remaining, read off
# a curve of loaded terminal volts -> minutes-to-trip measured on a real
# discharge. It makes no per-cell claim and needs no sag constant: a curve of
# LOADED volts already has sag baked into it. Zero percent is pinned to
# PACK_TRIP_MV, so moving the firmware floor re-zeros the gauge from one
# constant rather than needing a new table.
#
# SOC_CURVE_MV is used for its SHAPE only -- pack_soc_pct() normalises it, so
# the absolute minutes never reach the percentage. That matters because packs
# are swapped in and out of this rig as they charge, and two packs of the same
# type hold their voltage-vs-charge shape far better than they hold an absolute
# runtime. Absolute time remaining comes from PackTracker instead, which fits
# the rate of the pack actually fitted.
#
# History (full detail in CHANGELOG.md):
#   v1 initial version: runtime-fraction SoC curve + live PackTracker
###############################################################################

import time

TOOL_VERSION = 'pimd_pack.py v1'

# --------------------------------------------------------------------------
# Firmware-mirrored constants. These are the ONLY pack voltages in src/.
# Both must move together with the firmware's own pair (mcu/pimd_mcu.py):
# 500 mV is the hysteresis and nothing else depends on the re-arm level.
# --------------------------------------------------------------------------
PACK_TRIP_MV = 19_000       # firmware hard floor; the gauge's zero percent
PACK_REARM_MV = 19_500      # a returning pack must reach this to clear the latch
PACK_ABSENT_MV = 6_000      # below this the firmware assumes USB power, no pack

# --------------------------------------------------------------------------
# The discharge curve: loaded pack millivolts -> minutes of pulsing left
# before the pack reaches PACK_TRIP_MV.
#
# Measured 2026-08-12 on cal_2x11_v5 with the fan fitted, from the four session
# dumps of that day (279 '# pack_v:' samples), and generated by the --recal
# path below so that regenerating this table cannot shift the gauge for
# methodology reasons -- only because the pack changed. 118.1 min full-to-trip.
#
# EPOCH: this is the RETIRED, imbalanced pack, kept only until one run-down of
# a current pack replaces it. Its SHAPE is still the right shape (same cells,
# same chemistry, same load); only its absolute minutes belong to a pack that
# is no longer in the rig, and pack_soc_pct() normalises those away. Regenerate
# with
#   python pimd_pack.py --recal data/sessions/session_*.csv
# and paste the printed table and epoch back over these.
# --------------------------------------------------------------------------
PACK_CAL_EPOCH = '2026-08-12 (retired pack, shape only)'

SOC_CURVE_MV = [
    (23_800, 118.1), (23_600, 116.6), (23_400, 112.6), (23_200, 106.9),
    (23_000, 100.2), (22_800,  93.5), (22_600,  85.5), (22_400,  78.8),
    (22_200,  73.1), (22_000,  66.4), (21_800,  59.7), (21_600,  53.1),
    (21_400,  46.4), (21_200,  39.7), (21_000,  33.0), (20_800,  26.4),
    (20_600,  21.9), (20_400,  18.3), (20_200,  15.8), (20_000,  13.6),
    (19_800,  10.9), (19_600,   7.6), (19_400,   4.7), (19_200,   2.2),
    (19_000,   0.0),
]

# Gauge colours. Two palettes for one set of thresholds: the three GUI apps
# paint a fill behind dark text and need the pale end of the range, rawlog
# colours the label text itself and needs the readable end. Same breakpoints,
# so the apps never disagree about when a pack turns amber.
SOC_AMBER_PCT = 50.0
SOC_RED_PCT = 20.0
_FILL_COLOURS = ('#8ff0a4', '#f9f06b', '#f66151')   # green, amber, red
_TEXT_COLOURS = ('#26a269', '#c08800', '#f66151')


def _minutes_left(pack_mV):
    """Loaded pack millivolts -> minutes of pulsing left, piecewise-linear on
    SOC_CURVE_MV and clamped at both ends."""
    if pack_mV >= SOC_CURVE_MV[0][0]:
        return SOC_CURVE_MV[0][1]
    if pack_mV <= SOC_CURVE_MV[-1][0]:
        return SOC_CURVE_MV[-1][1]
    for (v1, m1), (v2, m2) in zip(SOC_CURVE_MV, SOC_CURVE_MV[1:]):
        if v2 <= pack_mV <= v1:
            return m2 + (m1 - m2) * (pack_mV - v2) / (v1 - v2)
    return SOC_CURVE_MV[-1][1]


def pack_soc_pct(pack_mV, trip_mV=PACK_TRIP_MV):
    """Loaded pack millivolts -> state of charge percent, 0 % at trip_mV.

    Normalised, so only the SHAPE of SOC_CURVE_MV is used and the absolute
    minutes of a particular pack's calibration never reach the percentage.
    Passing trip_mV re-zeros the whole gauge -- if the firmware floor moves,
    this one argument follows it and no table needs rewriting."""
    if pack_mV is None:
        return None
    t_trip = _minutes_left(trip_mV)
    span = SOC_CURVE_MV[0][1] - t_trip
    if span <= 0:
        return None
    soc = 100.0 * (_minutes_left(pack_mV) - t_trip) / span
    return max(0.0, min(100.0, soc))


def soc_colour(soc, for_text=False):
    """State of charge percent -> colour. for_text picks the darker palette."""
    palette = _TEXT_COLOURS if for_text else _FILL_COLOURS
    if soc is None:
        return palette[2]
    if soc >= SOC_AMBER_PCT:
        return palette[0]
    if soc >= SOC_RED_PCT:
        return palette[1]
    return palette[2]


def fmt_hm(minutes):
    """Minutes -> 'H:MM'. Returns None for None, so callers can branch once."""
    if minutes is None:
        return None
    minutes = max(0.0, minutes)
    h = int(minutes // 60)
    m = int(round(minutes - h * 60))
    if m == 60:
        h, m = h + 1, 0
    return '{0}:{1:02d}'.format(h, m)


class PackTracker:
    """Live discharge-rate tracker: fits a trailing window of pack readings and
    projects when the pack will reach PACK_TRIP_MV.

    This is what makes the time-remaining figure honest on a pack that has
    never been characterised. SOC_CURVE_MV supplies the percentage's shape; the
    absolute minutes come from the pack actually fitted, measured live.

    Packs are swapped in and out of this rig as they charge, so the tracker
    watches for the discontinuities that implies and drops history rather than
    fitting a line across two different packs:

      * a rise of more than SWAP_JUMP_MV between consecutive readings -- a
        charged pack fitted, or the load coming off,
      * the pack going absent (< PACK_ABSENT_MV, the firmware's USB-power case)
        and returning.

    Feed it note_pulse() from wherever measurement records are parsed. That,
    rather than any per-app streaming flag, is what defines 'pulsing': records
    flowing IS the coil running, in every one of the four apps, and it needs no
    app to expose its state machine. Readings taken while idle are not fitted,
    because the drive-off drain is roughly half the loaded rate and would
    flatter the estimate."""

    WINDOW_S = 900.0            # trailing fit window
    MIN_SPAN_S = 300.0          # refuse to quote a rate on less history than this
    MIN_RATE_MV_MIN = 3.0       # slower than this is not a discharge worth projecting
    SWAP_JUMP_MV = 500          # a rise this big is a new pack, not a measurement
    PULSE_IDLE_S = 30.0         # no records for this long => not pulsing

    def __init__(self):
        self._samples = []          # [(wall_seconds, pack_mV)] while pulsing
        self._last_pulse_wall = None
        self._last_mV = None
        self._absent = False
        self._held_rate = None      # last good mV/min, survives a pulsing gap
        self.last_reset_reason = 'never fitted'

    # -- feeding -----------------------------------------------------------
    def note_pulse(self):
        """Call on every measurement record (W / * / R). Cheap by design."""
        self._last_pulse_wall = time.time()

    def reset(self, reason='reset', drop_rate=True):
        """Forget the window. drop_rate=False keeps the held rate, which is what
        a mere pause in pulsing wants -- the pack has not changed, only the
        history has a hole in it."""
        self._samples = []
        self._last_mV = None
        if drop_rate:
            self._held_rate = None
        self.last_reset_reason = reason

    def add(self, pack_mV, now=None):
        """Apply one pack reading. Safe to call with None (no reading yet)."""
        if pack_mV is None:
            return
        now = time.time() if now is None else now

        if pack_mV < PACK_ABSENT_MV:
            if not self._absent:
                self.reset('pack absent')
            self._absent = True
            self._last_mV = pack_mV
            return
        if self._absent:
            self._absent = False
            self.reset('pack returned')

        if self._last_mV is not None and pack_mV - self._last_mV > self.SWAP_JUMP_MV:
            # A charged pack, or the load released. Either way the history
            # describes a different situation than the next sample will.
            self.reset('pack swap / load released')
        self._last_mV = pack_mV

        pulsing = (self._last_pulse_wall is not None
                   and now - self._last_pulse_wall < self.PULSE_IDLE_S)
        if not pulsing:
            # Keep the held rate: pausing does not change the pack, and a
            # stale window fitted across the gap would read far too flat.
            if self._samples:
                self.reset('pulsing stopped', drop_rate=False)
            return

        self._samples.append((now, pack_mV))
        cutoff = now - self.WINDOW_S
        self._samples = [s for s in self._samples if s[0] >= cutoff]

    # -- reading out -------------------------------------------------------
    def rate_mv_per_min(self):
        """Least-squares discharge rate over the window, mV/min, positive when
        discharging. None until there is enough history to mean anything."""
        if len(self._samples) < 3:
            return self._held_rate
        span = self._samples[-1][0] - self._samples[0][0]
        if span < self.MIN_SPAN_S:
            return self._held_rate
        t0 = self._samples[0][0]
        xs = [(t - t0) / 60.0 for t, _ in self._samples]
        ys = [float(mv) for _, mv in self._samples]
        n = len(xs)
        mx = sum(xs) / n
        my = sum(ys) / n
        sxx = sum((x - mx) ** 2 for x in xs)
        if sxx <= 0:
            return self._held_rate
        slope = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sxx
        rate = -slope
        if rate < self.MIN_RATE_MV_MIN:
            # Flat or rising: charging, resting, or simply too quiet to call.
            return self._held_rate
        self._held_rate = rate
        return rate

    def minutes_remaining(self, pack_mV, trip_mV=PACK_TRIP_MV):
        """(minutes, is_live). Live projection when a rate is available, else
        the SOC_CURVE_MV fallback flagged is_live=False so callers can mark it
        as the estimate from another pack that it is."""
        if pack_mV is None:
            return None, False
        rate = self.rate_mv_per_min()
        if rate:
            return max(0.0, (pack_mV - trip_mV) / rate), True
        return max(0.0, _minutes_left(pack_mV) - _minutes_left(trip_mV)), False


def pack_caption(pack_mV, lockout=False, tracker=None, trip_mV=PACK_TRIP_MV):
    """The one-line gauge caption: measured volts, then time left.

    Voltage first because it is the measured quantity and the percentage is
    derived from it. A tilde marks a fallback estimate -- one taken from
    SOC_CURVE_MV's retired-pack calibration rather than from the pack in the
    rig -- so a number that has not yet earned trust says so."""
    if pack_mV is None:
        return 'no pack reading'
    if lockout:
        return '{0:.2f} V  ·  LOCKED OUT'.format(pack_mV / 1000.0)
    volts = '{0:.2f} V'.format(pack_mV / 1000.0)
    if tracker is None:
        return volts
    minutes, live = tracker.minutes_remaining(pack_mV, trip_mV)
    hm = fmt_hm(minutes)
    if hm is None:
        return volts
    return '{0}  ·  {1}{2} left'.format(volts, '' if live else '~', hm)


# ---------------------------------------------------------------------------
# Recalibration CLI
# ---------------------------------------------------------------------------
def _recal(paths, trip_mV=PACK_TRIP_MV):
    """Rebuild SOC_CURVE_MV from session dumps and print it ready to paste.

    Reads the '# pack_v:' comment track pimd_classviz.py writes into every
    session dump.

    Works on discharge RATE rather than on elapsed time, which is what lets it
    take several sessions without stitching them. Each consecutive pair of
    readings gives one rate sample at one voltage; rates are binned by voltage
    and the median of each bin is taken, then minutes-to-trip is the integral
    of 1/rate from the trip upward. A rest between sessions simply contributes
    no sample rather than appearing as capacity from nowhere, and one bad
    reading loses to the median instead of moving the curve.

    Two things are cut rather than fitted:
      * samples after a LOCKOUT mark, because the drive is off past that point
        and the pack drains at roughly half the loaded rate, and
      * rates above MAX_RATE, which are load steps (the first reading of a
        session is taken before the coil starts) rather than discharge.

    Point it at ONE continuous run-down for the sharpest curve; several
    sessions of the same pack also work, blended by the median."""
    import datetime
    import re

    BIN_MV = 200
    MAX_RATE = 200.0        # mV/min above this is a load step, not a discharge

    rates = {}              # bin voltage -> [mV/min]
    used_files = 0
    for path in paths:
        track = []
        try:
            with open(path, errors='replace') as fh:
                for line in fh:
                    if 'LOCKOUT:' in line and line.startswith('# mark:'):
                        break       # drive off past here -- different regime
                    m = re.match(r'# pack_v: ([0-9T:\-.]+), ([0-9.]+), age_s=(\d+)', line)
                    if m:
                        mv = int(round(float(m.group(2)) * 1000))
                        if mv > PACK_ABSENT_MV:
                            track.append((datetime.datetime.fromisoformat(m.group(1)), mv))
        except OSError as exc:
            print('skipping {0}: {1}'.format(path, exc))
            continue
        track.sort()
        if len(track) < 5:
            continue
        used_files += 1
        span = (track[-1][0] - track[0][0]).total_seconds() / 60.0
        print('  {0}: {1} samples, {2:.1f} min, {3:.2f} -> {4:.2f} V'.format(
            path.split('/')[-1], len(track), span,
            track[0][1] / 1000.0, track[-1][1] / 1000.0))
        for (t1, v1), (t2, v2) in zip(track, track[1:]):
            dt = (t2 - t1).total_seconds() / 60.0
            if dt <= 0:
                continue
            rate = (v1 - v2) / dt
            if rate <= 0 or rate > MAX_RATE:
                continue        # recovery, noise, or a load step
            mid = (v1 + v2) / 2.0
            rates.setdefault(int(mid // BIN_MV) * BIN_MV, []).append(rate)

    if not rates:
        print('no usable "# pack_v:" tracks found')
        return 1

    def median(xs):
        xs = sorted(xs)
        n = len(xs)
        return xs[n // 2] if n % 2 else 0.5 * (xs[n // 2 - 1] + xs[n // 2])

    binned = {mv: median(v) for mv, v in rates.items()}
    lo = min(binned)
    hi = max(binned) + BIN_MV
    # Fill gaps by carrying the nearest measured bin, so one missing level
    # cannot cut the curve in half.
    levels = list(range(lo, hi, BIN_MV))
    for mv in levels:
        if mv not in binned:
            near = min(binned, key=lambda k: abs(k - mv))
            binned[mv] = binned[near]

    print('\n  rate by voltage bin (mV/min, median):')
    for mv in sorted(binned, reverse=True):
        print('    {0:5.2f} V  {1:6.1f}  (n={2})'.format(
            mv / 1000.0, binned[mv], len(rates.get(mv, []))))

    # Integrate 1/rate upward from the trip.
    curve = []
    minutes = 0.0
    for mv in sorted(binned):
        if mv + BIN_MV <= trip_mV:
            continue
        top = mv + BIN_MV
        bottom = max(mv, trip_mV)
        minutes += (top - bottom) / binned[mv]
        curve.append((top, minutes))
    curve.append((trip_mV, 0.0))
    curve.sort(key=lambda r: -r[0])

    print('\ntotal pulsing, {0:.2f} V -> {1:.2f} V = {2:.1f} min '
          '(from {3} session(s))'.format(
              curve[0][0] / 1000.0, trip_mV / 1000.0, curve[0][1], used_files))
    print('\nPACK_CAL_EPOCH = {0!r}\n\nSOC_CURVE_MV = ['.format(
        time.strftime('%Y-%m-%d')))
    for i in range(0, len(curve), 4):
        print('    ' + ' '.join('({0:_}, {1:5.1f}),'.format(mv, m)
                                for mv, m in curve[i:i + 4]))
    print(']')
    return 0


def main():
    import argparse
    ap = argparse.ArgumentParser(
        description='PIMD pack fuel gauge. With no arguments, prints the '
                    'current curve as a table for eyeballing.')
    ap.add_argument('--recal', nargs='+', metavar='SESSION_CSV',
                    help='rebuild SOC_CURVE_MV from session dumps and print it')
    args = ap.parse_args()
    if args.recal:
        return _recal(args.recal)
    print('{0}   calibration epoch: {1}'.format(TOOL_VERSION, PACK_CAL_EPOCH))
    print('trip {0:.2f} V   re-arm {1:.2f} V\n'.format(
        PACK_TRIP_MV / 1000.0, PACK_REARM_MV / 1000.0))
    print('  loaded V    SoC %    time left')
    for mv, _ in SOC_CURVE_MV:
        print('   {0:6.2f}     {1:5.1f}      {2}'.format(
            mv / 1000.0, pack_soc_pct(mv), fmt_hm(_minutes_left(mv))))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
