###############################################################################
# PIMD Signature Visualiser (ClassViz) — Mode 2 profile 4 (CLASSIFY_EP)
# Runs on Ubuntu desktop / laptop, standalone PyQt6 app (no .ui file)
#
# Connects to the board, sends Q4/G to start Mode 2 streaming, and displays
# a 5×9 heatmap of signed cell deviations from a captured air baseline.
# Includes a labelled-data logger for ML training data capture.
#
# Protocol: receives W4,<time_ms>,<ch0>,...,<ch44>
# Board firmware: pimd_mcu.py v4.04+
#
# v1.00 initial version: heatmap + baseline + labelled CSV logger + 3D surface
# v1.01 add Stats tab (per-cell value/mean/std, mV) + single-cell isolation mode
# v1.02 Resume Sweep now auto-sends G — sweep restarts immediately without extra click
# v1.03 Stats tab: Save table as CSV button (saves whatever is currently displayed)
###############################################################################

# pyright: reportOptionalMemberAccess=false
# pyright: reportAttributeAccessIssue=false

import os
import sys
import time
from datetime import datetime, date
from collections import deque

import numpy as np

os.environ.setdefault('QT_API', 'pyqt6')

from PyQt6.QtCore import QIODevice, QTimer, Qt  # noqa: E402
from PyQt6.QtSerialPort import QSerialPort  # noqa: E402
from PyQt6.QtWidgets import (  # noqa: E402
    QApplication, QCheckBox, QComboBox, QDoubleSpinBox, QFileDialog,
    QGroupBox, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSpinBox, QStackedWidget, QTabWidget, QTableWidget,
    QTableWidgetItem, QVBoxLayout, QWidget,
)

import pyqtgraph as pg  # noqa: E402

try:
    import pyqtgraph.opengl as gl
    _GL_AVAILABLE = True
except ImportError:
    _GL_AVAILABLE = False

APP_VERSION = '1.03'

N_BANDS    = 5
N_CELLS    = 9
N_CHANNELS = N_BANDS * N_CELLS   # 45
PROFILE_IDX = 4
REDRAW_MS   = 33    # ~30 Hz

CAPTURE_FRAMES_DEFAULT = 64
ROLLING_SECS_DEFAULT   = 3.0
DEFAULT_PORT = '/dev/ttyACM0'

# Threshold voltages: cell j ↔ (4.5 − 0.5·j) V
THRESHOLDS_V = tuple(4.5 - 0.5 * j for j in range(N_CELLS))

# Band metadata — matches pimd_mcu.py PROFILES[4] exactly.
# Each entry: (freq_hz, pulse_us, delays_us × 9)
BANDS_META = (
    (10601, 40.0, ( 8.56,  8.98,  9.37,  9.72, 10.08, 10.49, 10.96, 11.57, 12.53)),
    (17599, 30.0, ( 8.12,  8.54,  8.92,  9.27,  9.63, 10.02, 10.50, 11.10, 12.03)),
    (29201, 20.0, ( 7.62,  8.03,  8.40,  8.75,  9.11,  9.50,  9.96, 10.55, 11.46)),
    (43003, 10.0, ( 6.80,  7.22,  7.58,  7.93,  8.28,  8.66,  9.11,  9.70, 10.57)),
    (56992,  5.0, ( 6.03,  6.43,  6.78,  7.12,  7.46,  7.84,  8.28,  8.85,  9.71)),
)

BAND_LABELS = ['{0:.0f}µs/{1:.1f}kHz'.format(b[1], b[0] / 1000) for b in BANDS_META]
CELL_LABELS = ['{0:.1f}V'.format(v) for v in THRESHOLDS_V]

# Nominal baseline in µV: threshold_V × 1e6, uniform across all bands.
NOMINAL_BASELINE_UV = np.array(
    [[t * 1_000_000 for t in THRESHOLDS_V] for _ in range(N_BANDS)], dtype=float)

pg.setConfigOptions(background='w', foreground='k', antialias=True)

_R = int(Qt.AlignmentFlag.AlignRight) | int(Qt.AlignmentFlag.AlignVCenter)
_C = int(Qt.AlignmentFlag.AlignCenter)


def _fmt(uv):
    """µV → mV string with 1 d.p. and thousands comma."""
    return '{0:,.1f}'.format(uv / 1000.0)


def _csv_default_path():
    data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')
    return os.path.join(data_dir, 'signatures_{0}.csv'.format(date.today().strftime('%Y%m%d')))


def _write_csv_header(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    d_cols = ','.join('d{0:02d}'.format(i) for i in range(N_CHANNELS))
    r_cols = ','.join('r{0:02d}'.format(i) for i in range(N_CHANNELS))
    b_cols = ','.join('b{0:02d}'.format(i) for i in range(N_CHANNELS))
    with open(path, 'w') as f:
        f.write('# PIMD ClassViz labelled-data log — profile 4 (CLASSIFY_EP),'
                ' generated by pimd_classviz.py v{0}\n'.format(APP_VERSION))
        f.write('# Columns: timestamp, label, baseline_mode,\n')
        f.write('#   d00..d44 = signed deviation µV (band-major: index=band*9+cell),\n')
        f.write('#   r00..r44 = raw absolute µV,\n')
        f.write('#   b00..b44 = baseline mean µV used for delta\n')
        f.write('# Band order: 0=40µs/10.6kHz  1=30µs/17.6kHz  2=20µs/29.2kHz'
                '  3=10µs/43.0kHz  4=5µs/57.0kHz\n')
        f.write('# Cell j: threshold (4.5-0.5*j) V;'
                ' delays differ per band (see BANDS_META in source)\n')
        f.write('timestamp,label,baseline_mode,{0},{1},{2}\n'.format(d_cols, r_cols, b_cols))


class MainWindow(QMainWindow):
    MY_GREEN  = 'background-color: rgb(143, 240, 164);'
    MY_YELLOW = 'background-color: rgb(249, 240, 107);'
    MY_RED    = 'background-color: rgb(246,  97,  81);'

    def __init__(self):
        super().__init__()
        self.setWindowTitle('PIMD ClassViz v{0}'.format(APP_VERSION))

        # Serial
        self.serial = QSerialPort()
        self.serial.readyRead.connect(self.read_from_serial)
        self._last_cmd    = ''
        self._last_packet = ''

        # Data state — sweep
        self._latest_raw: 'np.ndarray | None' = None   # shape (45,)
        self._baseline_mean: 'np.ndarray | None' = None  # shape (5, 9)
        self._baseline_std:  'np.ndarray | None' = None  # shape (5, 9)
        self._baseline_mode = 'static'   # 'static' | 'rolling' | 'nominal'
        self._baseline_age: 'float | None' = None
        self._capture_buf: list = []
        self._capturing   = False
        self._capture_n   = CAPTURE_FRAMES_DEFAULT
        self._rolling_buf: deque = deque(maxlen=10_000)
        self._rolling_T   = ROLLING_SECS_DEFAULT

        self._freeze       = False
        self._autoscale    = True
        self._manual_range = 200_000.0
        self._display_mode = 'delta'     # 'raw' | 'delta' | 'z'
        self._3d_visible   = False

        self._continuous_log     = False
        self._csv_header_written = False
        self._csv_rows           = 0
        self._frame_count        = 0

        # Data state — stats + single-cell
        self._mode        = 'sweep'     # 'sweep' | 'single_cell'
        self._freeze_stats = False
        self._sc_buf: deque = deque(maxlen=1000)   # Mode 1 value_uV readings

        self._setup_colormaps()
        self._build_ui()

        self._redraw_timer = QTimer()
        self._redraw_timer.setInterval(REDRAW_MS)
        self._redraw_timer.timeout.connect(self._redraw)
        self._redraw_timer.start()

    # ------------------------------------------------------------------
    # Colormaps
    # ------------------------------------------------------------------
    def _setup_colormaps(self):
        try:
            self.cm_div = pg.colormap.get('RdBu_r', source='matplotlib')
        except Exception:
            try:
                self.cm_div = pg.colormap.get('RdBu_r')
            except Exception:
                self.cm_div = pg.ColorMap(
                    pos=np.array([0.0, 0.5, 1.0]),
                    color=np.array([[0, 0, 220, 255], [255, 255, 255, 255],
                                    [220, 0, 0, 255]], dtype=np.uint8))
        try:
            self.cm_seq = pg.colormap.get('plasma', source='matplotlib')
        except Exception:
            try:
                self.cm_seq = pg.colormap.get('plasma')
            except Exception:
                self.cm_seq = pg.colormap.get('viridis')

    # ------------------------------------------------------------------
    # UI
    # ------------------------------------------------------------------
    def _build_ui(self):
        central = QWidget()
        layout  = QVBoxLayout(central)

        # Top bar — always visible on both tabs
        row1 = QHBoxLayout()
        row1.addWidget(QLabel('Port:'))
        self.le_port = QLineEdit(DEFAULT_PORT)
        self.le_port.setMaximumWidth(150)
        row1.addWidget(self.le_port)

        self.pb_connect = QPushButton('Not Connected')
        self.pb_connect.setStyleSheet(self.MY_YELLOW)
        self.pb_connect.clicked.connect(self.connect_port)
        row1.addWidget(self.pb_connect)

        self.pb_start = QPushButton('Stopped')
        self.pb_start.setStyleSheet(self.MY_YELLOW)
        self.pb_start.clicked.connect(self.start_stop)
        row1.addWidget(self.pb_start)

        self.header_label = QLabel('Profile 4 — CLASSIFY_EP (5 bands × 9 cells)')
        row1.addWidget(self.header_label, stretch=1)
        layout.addLayout(row1)

        # Tab widget
        self.tabs = QTabWidget()
        self.tabs.addTab(self._build_heatmap_tab(), 'Heatmap')
        self.tabs.addTab(self._build_stats_tab(),   'Stats && Isolation')
        layout.addWidget(self.tabs, stretch=1)

        self.setCentralWidget(central)
        self.statusBar().showMessage('Not connected')

    # ------------------------------------------------------------------
    # Tab 0 — Heatmap
    # ------------------------------------------------------------------
    def _build_heatmap_tab(self):
        w      = QWidget()
        layout = QVBoxLayout(w)

        # Row 2 — display + baseline controls
        row2 = QHBoxLayout()
        row2.addWidget(QLabel('Display:'))
        self.cb_display = QComboBox()
        self.cb_display.addItems(['Δ deviation [default]', 'Z normalised', 'RAW abs µV'])
        self.cb_display.setCurrentIndex(0)
        self.cb_display.currentIndexChanged.connect(self._on_display_changed)
        row2.addWidget(self.cb_display)

        row2.addWidget(QLabel('Baseline:'))
        self.cb_baseline = QComboBox()
        self.cb_baseline.addItems(['Static capture', 'Rolling median', 'Nominal thresholds'])
        self.cb_baseline.currentIndexChanged.connect(self._on_baseline_mode_changed)
        row2.addWidget(self.cb_baseline)

        row2.addWidget(QLabel('N='))
        self.sp_capture_n = QSpinBox()
        self.sp_capture_n.setRange(1, 4096)
        self.sp_capture_n.setValue(CAPTURE_FRAMES_DEFAULT)
        row2.addWidget(self.sp_capture_n)

        self.pb_capture = QPushButton('Capture baseline')
        self.pb_capture.clicked.connect(self._start_capture)
        row2.addWidget(self.pb_capture)

        self.pb_clear = QPushButton('Clear baseline')
        self.pb_clear.clicked.connect(self.clear_baseline)
        row2.addWidget(self.pb_clear)

        self.pb_freeze = QPushButton('Freeze')
        self.pb_freeze.setCheckable(True)
        self.pb_freeze.toggled.connect(self._on_freeze_toggled)
        row2.addWidget(self.pb_freeze)
        layout.addLayout(row2)

        # Row 3 — scale + rolling T + baseline info
        row3 = QHBoxLayout()
        self.cb_autoscale = QCheckBox('Auto ±')
        self.cb_autoscale.setChecked(True)
        self.cb_autoscale.toggled.connect(self._on_autoscale_toggled)
        row3.addWidget(self.cb_autoscale)

        row3.addWidget(QLabel('Range (µV):'))
        self.sp_range = QDoubleSpinBox()
        self.sp_range.setRange(100, 5_000_000)
        self.sp_range.setSingleStep(10_000)
        self.sp_range.setDecimals(0)
        self.sp_range.setValue(self._manual_range)
        self.sp_range.setEnabled(False)
        self.sp_range.valueChanged.connect(self._on_range_changed)
        row3.addWidget(self.sp_range)

        row3.addWidget(QLabel('Rolling T (s):'))
        self.sp_rolling_t = QDoubleSpinBox()
        self.sp_rolling_t.setRange(0.5, 60.0)
        self.sp_rolling_t.setSingleStep(0.5)
        self.sp_rolling_t.setDecimals(1)
        self.sp_rolling_t.setValue(ROLLING_SECS_DEFAULT)
        self.sp_rolling_t.valueChanged.connect(self._on_rolling_t_changed)
        row3.addWidget(self.sp_rolling_t)

        self.lbl_baseline_info = QLabel('No baseline')
        row3.addWidget(self.lbl_baseline_info, stretch=1)

        self.lbl_scale = QLabel('Scale: —')
        row3.addWidget(self.lbl_scale)
        layout.addLayout(row3)

        # Main view stack (2D heatmap / 3D surface)
        self.stack = QStackedWidget()
        self.stack.addWidget(self._build_heatmap_widget())   # index 0
        self.stack.addWidget(self._build_3d_widget())        # index 1
        layout.addWidget(self.stack, stretch=1)

        btn_toggle = QHBoxLayout()
        self.pb_toggle3d = QPushButton('Switch to 3D Surface')
        self.pb_toggle3d.clicked.connect(self._toggle_3d)
        btn_toggle.addWidget(self.pb_toggle3d)
        btn_toggle.addStretch(1)
        layout.addLayout(btn_toggle)

        # Zero-crossing summary
        self.lbl_crossings = QLabel('Crossings: —')
        layout.addWidget(self.lbl_crossings)

        # ML bridge — row A
        ml_a = QHBoxLayout()
        ml_a.addWidget(QLabel('Label:'))
        self.le_label = QLineEdit()
        self.le_label.setPlaceholderText('e.g. air / silver_coin / stainless_bolt')
        ml_a.addWidget(self.le_label, stretch=1)

        self.pb_snapshot = QPushButton('Record Snapshot')
        self.pb_snapshot.clicked.connect(self._record_snapshot)
        ml_a.addWidget(self.pb_snapshot)

        self.cb_continuous = QCheckBox('Log Continuously')
        self.cb_continuous.toggled.connect(self._on_continuous_toggled)
        ml_a.addWidget(self.cb_continuous)

        self.lbl_rows = QLabel('Rows: 0')
        ml_a.addWidget(self.lbl_rows)
        layout.addLayout(ml_a)

        # ML bridge — row B (CSV path)
        ml_b = QHBoxLayout()
        ml_b.addWidget(QLabel('CSV:'))
        self.le_csv = QLineEdit(_csv_default_path())
        ml_b.addWidget(self.le_csv, stretch=1)
        pb_browse = QPushButton('Browse…')
        pb_browse.clicked.connect(self._browse_csv)
        ml_b.addWidget(pb_browse)
        layout.addLayout(ml_b)

        return w

    def _build_heatmap_widget(self):
        self.gw = pg.GraphicsLayoutWidget()
        self.plot = self.gw.addPlot()
        self.plot.invertY(True)
        self.plot.setDefaultPadding(0)

        self.img = pg.ImageItem()
        self.img.setColorMap(self.cm_div)
        self.plot.addItem(self.img)

        ax_b = self.plot.getAxis('bottom')
        ax_b.setTicks([[(j + 0.5, CELL_LABELS[j]) for j in range(N_CELLS)]])
        ax_b.setLabel('Threshold')

        ax_l = self.plot.getAxis('left')
        ax_l.setTicks([[(b + 0.5, BAND_LABELS[b]) for b in range(N_BANDS)]])
        ax_l.setLabel('Band')

        self.plot.setXRange(0, N_CELLS, padding=0)
        self.plot.setYRange(0, N_BANDS, padding=0)

        self.plot.scene().sigMouseMoved.connect(self._on_mouse_move)
        return self.gw

    def _build_3d_widget(self):
        if not _GL_AVAILABLE:
            w   = QWidget()
            lbl = QLabel('3D view requires PyOpenGL — install python3-pyopengl')
            lbl.setAlignment(Qt.AlignmentFlag.AlignCenter)
            QVBoxLayout(w).addWidget(lbl)
            return w

        self.gl_widget = gl.GLViewWidget()
        self.gl_widget.setCameraPosition(distance=15, elevation=30, azimuth=45)
        self._surface = gl.GLSurfacePlotItem(
            x=np.arange(N_CELLS, dtype=float),
            y=np.arange(N_BANDS, dtype=float),
            z=np.zeros((N_CELLS, N_BANDS)),
            smooth=False,
        )
        self.gl_widget.addItem(self._surface)
        return self.gl_widget

    # ------------------------------------------------------------------
    # Tab 1 — Stats & Isolation
    # ------------------------------------------------------------------
    def _build_stats_tab(self):
        w      = QWidget()
        layout = QVBoxLayout(w)

        # Controls row
        ctrl = QHBoxLayout()
        self.pb_freeze_stats = QPushButton('Freeze')
        self.pb_freeze_stats.setCheckable(True)
        self.pb_freeze_stats.toggled.connect(self._on_freeze_stats_toggled)
        ctrl.addWidget(self.pb_freeze_stats)

        ctrl.addWidget(QLabel('Window:'))
        self.sp_stats_window = QDoubleSpinBox()
        self.sp_stats_window.setRange(0.5, 60.0)
        self.sp_stats_window.setSingleStep(0.5)
        self.sp_stats_window.setDecimals(1)
        self.sp_stats_window.setValue(ROLLING_SECS_DEFAULT)
        self.sp_stats_window.setSuffix(' s')
        ctrl.addWidget(self.sp_stats_window)

        pb_save_stats = QPushButton('Save table CSV…')
        pb_save_stats.clicked.connect(self._save_stats_csv)
        ctrl.addWidget(pb_save_stats)

        ctrl.addStretch(1)
        ctrl.addWidget(QLabel('All values in mV · 1 d.p.'))
        layout.addLayout(ctrl)

        # Stats table: Band | Threshold | Delay µs | Latest mV | Mean mV | Std mV
        self.tbl_stats = QTableWidget(N_CHANNELS, 6)
        self.tbl_stats.setHorizontalHeaderLabels(
            ['Band', 'Threshold', 'Delay (µs)', 'Latest (mV)', 'Mean (mV)', 'Std (mV)'])
        self.tbl_stats.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.tbl_stats.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.tbl_stats.setAlternatingRowColors(True)

        for b in range(N_BANDS):
            freq_hz, pulse_us, delays = BANDS_META[b]
            for c in range(N_CELLS):
                row = b * N_CELLS + c
                for col, text in enumerate([BAND_LABELS[b],
                                            CELL_LABELS[c],
                                            '{0:.2f}'.format(delays[c])]):
                    item = QTableWidgetItem(text)
                    item.setTextAlignment(_C)
                    self.tbl_stats.setItem(row, col, item)
                for col in range(3, 6):
                    item = QTableWidgetItem('—')
                    item.setTextAlignment(_R)
                    self.tbl_stats.setItem(row, col, item)

        layout.addWidget(self.tbl_stats, stretch=1)

        # ── Single-cell isolation ─────────────────────────────────────
        grp = QGroupBox('Single-cell isolation  '
                        '(stop sweep → run one fixed freq/pulse/delay via Mode 1)')
        grp_layout = QVBoxLayout(grp)

        sc_row1 = QHBoxLayout()
        sc_row1.addWidget(QLabel('Band:'))
        self.cb_sc_band = QComboBox()
        for label in BAND_LABELS:
            self.cb_sc_band.addItem(label)
        self.cb_sc_band.currentIndexChanged.connect(self._on_sc_band_changed)
        sc_row1.addWidget(self.cb_sc_band)

        sc_row1.addWidget(QLabel('Cell:'))
        self.cb_sc_cell = QComboBox()
        sc_row1.addWidget(self.cb_sc_cell)

        self.lbl_sc_cell_info = QLabel('')
        sc_row1.addWidget(self.lbl_sc_cell_info, stretch=1)

        sc_row1.addWidget(QLabel('Downsample:'))
        self.sp_sc_ds = QSpinBox()
        self.sp_sc_ds.setRange(1, 4096)
        self.sp_sc_ds.setValue(256)
        sc_row1.addWidget(self.sp_sc_ds)
        grp_layout.addLayout(sc_row1)

        sc_row2 = QHBoxLayout()
        self.pb_run_single = QPushButton('Run Single Cell')
        self.pb_run_single.setStyleSheet(self.MY_YELLOW)
        self.pb_run_single.clicked.connect(self._run_single_cell)
        sc_row2.addWidget(self.pb_run_single)

        self.pb_resume_sweep = QPushButton('Resume Sweep')
        self.pb_resume_sweep.clicked.connect(self._resume_sweep)
        self.pb_resume_sweep.setEnabled(False)
        sc_row2.addWidget(self.pb_resume_sweep)
        sc_row2.addStretch(1)
        grp_layout.addLayout(sc_row2)

        # Single-cell readout (Mode 1 `*` records)
        sc_row3 = QHBoxLayout()
        self.lbl_sc_value   = QLabel('Value: —')
        self.lbl_sc_hw_std  = QLabel('HW σ: —')
        self.lbl_sc_run_mean = QLabel('Run mean: —')
        self.lbl_sc_run_std  = QLabel('Run σ: —')
        self.lbl_sc_n        = QLabel('N=0')
        for lbl in (self.lbl_sc_value, self.lbl_sc_hw_std,
                    self.lbl_sc_run_mean, self.lbl_sc_run_std, self.lbl_sc_n):
            sc_row3.addWidget(lbl)
        sc_row3.addStretch(1)
        grp_layout.addLayout(sc_row3)

        layout.addWidget(grp)

        # Populate cell combo for band 0
        self._on_sc_band_changed(0)
        return w

    # ------------------------------------------------------------------
    # Serial
    # ------------------------------------------------------------------
    def serial_open(self, flag):
        if flag:
            port = self.le_port.text()
            if port.startswith('/dev/'):
                port = port[5:]
            self.serial.setPortName(port)
            self.serial.setBaudRate(115200)
            self.serial.setDataBits(QSerialPort.DataBits.Data8)
            self.serial.setParity(QSerialPort.Parity.NoParity)
            self.serial.setStopBits(QSerialPort.StopBits.OneStop)
            self.serial.setFlowControl(QSerialPort.FlowControl.NoFlowControl)
            return self.serial.open(QIODevice.OpenModeFlag.ReadWrite)
        else:
            self.serial.close()
            return True

    def connect_port(self):
        if self.pb_connect.text() != 'Connected':
            if self.serial_open(True):
                self.pb_connect.setText('Connected')
                self.pb_connect.setStyleSheet(self.MY_GREEN)
                self.send_command('E')
                self.send_command('Q{0}'.format(PROFILE_IDX))
                self.statusBar().showMessage('Connected — Q4 sent')
            else:
                self.pb_connect.setText('Port Error')
                self.pb_connect.setStyleSheet(self.MY_RED)
                self.statusBar().showMessage('Could not open port')
        else:
            self.start_stop(force_stop=True)
            self.serial_open(False)
            self.pb_connect.setText('Not Connected')
            self.pb_connect.setStyleSheet(self.MY_YELLOW)
            self.statusBar().showMessage('Disconnected')

    def read_from_serial(self):
        while self.serial.canReadLine():
            raw = self.serial.readLine().data().decode('utf-8', errors='replace').rstrip()
            if raw:
                self.process_packet(raw)

    def send_command(self, text):
        self.serial.write((text + '\n').encode())
        self._last_cmd = text

    # ------------------------------------------------------------------
    # Start / stop
    # ------------------------------------------------------------------
    def start_stop(self, force_stop=False):
        if force_stop or self.pb_start.text() == 'Running':
            self.send_command('E')
            self.pb_start.setText('Stopped')
            self.pb_start.setStyleSheet(self.MY_YELLOW)
            if self._mode == 'single_cell':
                self._mode = 'sweep'
                self._update_sc_button_states()
        else:
            if not self.serial.isOpen():
                return
            if self._mode == 'single_cell':
                # Auto-exit single-cell before resuming sweep
                self._mode = 'sweep'
                self._update_sc_button_states()
                self.send_command('Q{0}'.format(PROFILE_IDX))
            self.send_command('G')
            self.pb_start.setText('Running')
            self.pb_start.setStyleSheet(self.MY_GREEN)

    # ------------------------------------------------------------------
    # Packet handling
    # ------------------------------------------------------------------
    def process_packet(self, line):
        self._last_packet = line

        # Normalise separator — firmware uses ',' but tolerate ', '
        line = line.replace(', ', ',')

        if not line:
            return

        # Mode 1 single-cell output: *<time_ms>,<value_uV>,<stddev_uV>,<freq>,<pulse>,<delay>,<ds>
        if self._mode == 'single_cell' and line[0] == '*':
            parts = line[1:].split(',')
            if len(parts) == 7:
                try:
                    value_uV  = float(parts[1])
                    stddev_uV = float(parts[2])
                    self._sc_buf.append(value_uV)
                    arr = np.array(self._sc_buf)
                    self.lbl_sc_value.setText('Value: {0} mV'.format(_fmt(value_uV)))
                    self.lbl_sc_hw_std.setText('HW σ: {0} mV'.format(_fmt(stddev_uV)))
                    self.lbl_sc_run_mean.setText(
                        'Run mean: {0} mV'.format(_fmt(arr.mean())))
                    self.lbl_sc_run_std.setText(
                        'Run σ: {0} mV'.format(_fmt(arr.std())))
                    self.lbl_sc_n.setText('N={0}'.format(len(arr)))
                except (ValueError, IndexError):
                    pass
            self._update_status()
            return

        # Mode 2 sweep: W4,<time_ms>,<ch0>,...,<ch44>
        if len(line) < 2 or line[0] != 'W' or not line[1].isdigit():
            return

        parts = line.split(',')
        try:
            w_idx = int(parts[0][1:])
            if w_idx != PROFILE_IDX:
                return
            if len(parts) != 2 + N_CHANNELS:
                return
            raw = np.array([int(parts[2 + i]) for i in range(N_CHANNELS)], dtype=float)
        except (ValueError, IndexError) as e:
            self.statusBar().showMessage('W parse error: {0}'.format(e))
            return

        self._latest_raw = raw
        self._frame_count += 1
        self._rolling_buf.append((time.time(), raw))

        if self._capturing:
            self._capture_buf.append(raw.copy())
            n = len(self._capture_buf)
            self.pb_capture.setText('Capturing {0}/{1}…'.format(n, self._capture_n))
            if n >= self._capture_n:
                self._finalise_capture()

        if self._continuous_log:
            raw_5x9 = raw.reshape(N_BANDS, N_CELLS)
            mean, _ = self._get_current_baseline()
            delta = (raw_5x9 - mean) if mean is not None else np.zeros((N_BANDS, N_CELLS))
            self._append_csv_row(self.le_label.text(), delta, raw_5x9, mean)

        self._update_status()

    # ------------------------------------------------------------------
    # Baseline
    # ------------------------------------------------------------------
    def _start_capture(self):
        self._capture_n   = self.sp_capture_n.value()
        self._capture_buf = []
        self._capturing   = True
        self.pb_capture.setText('Capturing 0/{0}…'.format(self._capture_n))
        self.pb_capture.setStyleSheet(self.MY_YELLOW)

    def _finalise_capture(self):
        arr = np.array(self._capture_buf, dtype=float)
        self._baseline_mean = arr.mean(0).reshape(N_BANDS, N_CELLS)
        self._baseline_std  = arr.std(0).reshape(N_BANDS, N_CELLS)
        self._baseline_age  = time.time()
        self._capturing     = False
        self._capture_buf   = []
        self.pb_capture.setText('Capture baseline')
        self.pb_capture.setStyleSheet('')

    def clear_baseline(self):
        self._baseline_mean = None
        self._baseline_std  = None
        self._baseline_age  = None

    def _get_current_baseline(self):
        """Return (mean_5x9, std_5x9) or (None, None)."""
        if self._baseline_mode == 'static':
            return self._baseline_mean, self._baseline_std

        if self._baseline_mode == 'nominal':
            return NOMINAL_BASELINE_UV.copy(), np.zeros((N_BANDS, N_CELLS))

        cutoff = time.time() - self._rolling_T
        frames = [arr for ts, arr in self._rolling_buf if ts >= cutoff]
        if not frames:
            return None, None
        mat  = np.array(frames, dtype=float)
        mean = np.median(mat, axis=0).reshape(N_BANDS, N_CELLS)
        std  = mat.std(axis=0).reshape(N_BANDS, N_CELLS)
        return mean, std

    # ------------------------------------------------------------------
    # Display computation (heatmap)
    # ------------------------------------------------------------------
    def _compute_display_matrix(self, raw_5x9, mean, std):
        if self._display_mode == 'raw':
            return raw_5x9.copy()
        if mean is None:
            return np.zeros((N_BANDS, N_CELLS))
        delta = raw_5x9 - mean
        if self._display_mode == 'delta':
            return delta
        safe_std = np.where(std is not None and std > 1.0, std, 1.0)
        return delta / safe_std

    def _update_heatmap(self, matrix):
        if self._autoscale:
            lim = float(np.max(np.abs(matrix)))
            if lim < 1.0:
                lim = 1.0
        else:
            lim = self._manual_range

        if self._display_mode == 'raw':
            self.img.setColorMap(self.cm_seq)
            self.img.setImage(matrix.T, levels=(0.0, float(matrix.max()) * 1.05 + 1.0))
            self.lbl_scale.setText('Scale: 0…{0:.0f} mV'.format(matrix.max() / 1000))
        else:
            self.img.setColorMap(self.cm_div)
            self.img.setImage(matrix.T, levels=(-lim, lim))
            unit = 'σ' if self._display_mode == 'z' else 'mV'
            val  = lim if self._display_mode == 'z' else lim / 1000
            self.lbl_scale.setText('Scale: ±{0:.2f} {1}'.format(val, unit))

    def _update_3d(self, matrix):
        # Note: the 5-row (band) axis is coarse — interpolation between 5 bands
        # is cosmetic smoothing only, not real data.
        if not _GL_AVAILABLE or not hasattr(self, '_surface'):
            return
        lim = max(float(np.abs(matrix).max()), 1.0)
        normed = np.clip((matrix + lim) / (2.0 * lim), 0.0, 1.0)
        try:
            rgba = self.cm_div.map(normed.T.flatten(), mode='float')
            rgba = rgba.reshape(N_CELLS, N_BANDS, 4)
            self._surface.setData(z=matrix.T, colors=rgba)
        except Exception:
            self._surface.setData(z=matrix.T)

    # ------------------------------------------------------------------
    # Stats table update
    # ------------------------------------------------------------------
    def _update_stats_table(self):
        if self._freeze_stats or self._latest_raw is None:
            return

        raw    = self._latest_raw   # (45,)
        window = self.sp_stats_window.value()
        cutoff = time.time() - window
        frames = [arr for ts, arr in self._rolling_buf if ts >= cutoff]

        if len(frames) >= 2:
            mat   = np.array(frames, dtype=float)
            means = mat.mean(0)
            stds  = mat.std(0)
        else:
            means = raw.copy()
            stds  = np.zeros(N_CHANNELS)

        for i in range(N_CHANNELS):
            self.tbl_stats.item(i, 3).setText(_fmt(raw[i]))
            self.tbl_stats.item(i, 4).setText(_fmt(means[i]))
            self.tbl_stats.item(i, 5).setText(_fmt(stds[i]))

    def _save_stats_csv(self):
        data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')
        default = os.path.join(data_dir,
            'stats_{0}.csv'.format(datetime.now().strftime('%Y%m%d_%H%M%S')))
        path, _ = QFileDialog.getSaveFileName(
            self, 'Save stats table', default, 'CSV files (*.csv)')
        if not path:
            return
        headers = ['Band', 'Threshold', 'Delay (us)',
                   'Latest (mV)', 'Mean (mV)', 'Std (mV)']
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as f:
            f.write(','.join(headers) + '\n')
            for row in range(self.tbl_stats.rowCount()):
                f.write(','.join(
                    self.tbl_stats.item(row, col).text()
                    for col in range(self.tbl_stats.columnCount())) + '\n')
        self.statusBar().showMessage('Stats table saved: {0}'.format(path))

    # ------------------------------------------------------------------
    # Redraw (30 Hz timer)
    # ------------------------------------------------------------------
    def _redraw(self):
        if self._latest_raw is None:
            return

        # Always update heatmap so it's current when user switches back to it
        if not self._freeze:
            mean, std = self._get_current_baseline()
            raw_5x9   = self._latest_raw.reshape(N_BANDS, N_CELLS)
            matrix    = self._compute_display_matrix(raw_5x9, mean, std)
            self._update_heatmap(matrix)
            if self._3d_visible:
                self._update_3d(matrix)
            self._update_baseline_label(mean)
            delta_5x9 = (raw_5x9 - mean) if mean is not None else None
            self._update_crossings(delta_5x9)

        # Stats table — only compute when that tab is visible
        if self.tabs.currentIndex() == 1:
            self._update_stats_table()

    def _update_baseline_label(self, mean):
        mode = self._baseline_mode
        if mode == 'nominal':
            self.lbl_baseline_info.setText('Baseline: Nominal thresholds')
        elif mode == 'rolling':
            now   = time.time()
            count = sum(1 for ts, _ in self._rolling_buf if ts >= now - self._rolling_T)
            self.lbl_baseline_info.setText(
                'Baseline: Rolling {0:.1f}s ({1} frames)'.format(self._rolling_T, count))
        else:
            if self._capturing:
                self.lbl_baseline_info.setText('Baseline: Capturing…')
            elif mean is None:
                self.lbl_baseline_info.setText('Baseline: None — click Capture')
            else:
                age = (time.time() - self._baseline_age) if self._baseline_age else 0
                self.lbl_baseline_info.setText(
                    'Baseline: Static ({0}fr, {1:.0f}s ago)'.format(self._capture_n, age))

    def _update_crossings(self, delta_5x9):
        if delta_5x9 is None:
            self.lbl_crossings.setText('Crossings: no baseline')
            return
        crossings = self._compute_crossings(delta_5x9)
        parts = []
        for b, cross in enumerate(crossings):
            pol = '+' if delta_5x9[b, 0] > 0 else '−'
            if cross is not None:
                thresh_v = 4.5 - 0.5 * cross
                parts.append('B{0}:{1}↔{2:.2f}V'.format(b, pol, thresh_v))
            else:
                parts.append('B{0}:{1}'.format(b, pol))
        self.lbl_crossings.setText('Crossings:  ' + '   '.join(parts))

    # ------------------------------------------------------------------
    # Zero-crossing
    # ------------------------------------------------------------------
    def _compute_crossings(self, delta_5x9):
        crossings = []
        for b in range(N_BANDS):
            row   = delta_5x9[b]
            found = None
            for j in range(N_CELLS - 1):
                if row[j] * row[j + 1] < 0:
                    denom = abs(row[j]) + abs(row[j + 1])
                    frac  = abs(row[j]) / denom if denom > 0 else 0.5
                    found = j + frac
                    break
            crossings.append(found)
        return crossings

    # ------------------------------------------------------------------
    # Single-cell isolation
    # ------------------------------------------------------------------
    def _on_sc_band_changed(self, band_idx):
        freq_hz, pulse_us, delays = BANDS_META[band_idx]
        self.cb_sc_cell.clear()
        for c, (delay, thresh) in enumerate(zip(delays, THRESHOLDS_V)):
            self.cb_sc_cell.addItem('{0:.1f}V / {1:.2f}µs'.format(thresh, delay))
        self._update_sc_info()

    def _update_sc_info(self):
        b = self.cb_sc_band.currentIndex()
        c = self.cb_sc_cell.currentIndex()
        if b < 0 or c < 0:
            return
        freq_hz, pulse_us, delays = BANDS_META[b]
        self.lbl_sc_cell_info.setText(
            '→ {0:.3f} kHz  {1:.0f} µs pulse  delay {2:.2f} µs'.format(
                freq_hz / 1000, pulse_us, delays[c]))

    def _run_single_cell(self):
        if not self.serial.isOpen():
            self.statusBar().showMessage('Not connected')
            return
        b = self.cb_sc_band.currentIndex()
        c = self.cb_sc_cell.currentIndex()
        freq_hz, pulse_us, delays = BANDS_META[b]
        delay_us = delays[c]
        freq_khz = freq_hz / 1000.0
        ds       = self.sp_sc_ds.value()

        self.send_command('E')
        self.send_command('*{0:.3f},{1:.1f},{2:.2f},{3}'.format(
            freq_khz, pulse_us, delay_us, ds))
        self.send_command('S')

        self._mode = 'single_cell'
        self._sc_buf.clear()
        for lbl in (self.lbl_sc_value, self.lbl_sc_hw_std,
                    self.lbl_sc_run_mean, self.lbl_sc_run_std):
            lbl.setText(lbl.text().split(':')[0] + ': —')
        self.lbl_sc_n.setText('N=0')

        self.pb_run_single.setText('Running: {0} {1}'.format(
            BAND_LABELS[b], CELL_LABELS[c]))
        self.pb_run_single.setStyleSheet(self.MY_GREEN)
        self.pb_start.setText('Stopped')
        self.pb_start.setStyleSheet(self.MY_YELLOW)
        self._update_sc_button_states()

    def _resume_sweep(self):
        self.send_command('E')
        self._mode = 'sweep'
        self.send_command('Q{0}'.format(PROFILE_IDX))
        self.send_command('G')
        self.pb_start.setText('Running')
        self.pb_start.setStyleSheet(self.MY_GREEN)
        self.pb_run_single.setText('Run Single Cell')
        self.pb_run_single.setStyleSheet(self.MY_YELLOW)
        self._update_sc_button_states()
        self.statusBar().showMessage('Sweep running')

    def _update_sc_button_states(self):
        in_sc = (self._mode == 'single_cell')
        self.pb_run_single.setEnabled(not in_sc)
        self.pb_resume_sweep.setEnabled(in_sc)

    def _on_freeze_stats_toggled(self, checked):
        self._freeze_stats = checked
        self.pb_freeze_stats.setStyleSheet(self.MY_YELLOW if checked else '')

    # ------------------------------------------------------------------
    # ML bridge
    # ------------------------------------------------------------------
    def _record_snapshot(self):
        if self._latest_raw is None:
            self.statusBar().showMessage('No data to record')
            return
        raw_5x9 = self._latest_raw.reshape(N_BANDS, N_CELLS)
        mean, _ = self._get_current_baseline()
        delta   = (raw_5x9 - mean) if mean is not None else np.zeros((N_BANDS, N_CELLS))
        self._append_csv_row(self.le_label.text(), delta, raw_5x9, mean)
        self.statusBar().showMessage('Snapshot recorded — row {0}'.format(self._csv_rows))

    def _on_continuous_toggled(self, checked):
        self._continuous_log = checked

    def _append_csv_row(self, label, delta_5x9, raw_5x9, baseline_5x9):
        path = self.le_csv.text()
        if not path:
            return
        if not self._csv_header_written:
            if not os.path.exists(path):
                _write_csv_header(path)
            self._csv_header_written = True
        bl  = baseline_5x9 if baseline_5x9 is not None else np.zeros((N_BANDS, N_CELLS))
        ts  = datetime.now().isoformat(timespec='milliseconds')
        row = [ts, label, self._baseline_mode]
        row += delta_5x9.flatten().astype(int).tolist()
        row += raw_5x9.flatten().astype(int).tolist()
        row += bl.flatten().astype(int).tolist()
        with open(path, 'a') as f:
            f.write(','.join(str(v) for v in row) + '\n')
        self._csv_rows += 1
        self.lbl_rows.setText('Rows: {0}'.format(self._csv_rows))

    def _browse_csv(self):
        path, _ = QFileDialog.getSaveFileName(
            self, 'Select CSV file', self.le_csv.text(), 'CSV files (*.csv)')
        if path:
            self.le_csv.setText(path)
            self._csv_header_written = False

    # ------------------------------------------------------------------
    # Toggle 2D / 3D
    # ------------------------------------------------------------------
    def _toggle_3d(self):
        if not _GL_AVAILABLE:
            self.statusBar().showMessage('3D view not available — install python3-pyopengl')
            return
        self._3d_visible = not self._3d_visible
        self.stack.setCurrentIndex(1 if self._3d_visible else 0)
        self.pb_toggle3d.setText(
            'Switch to 2D Heatmap' if self._3d_visible else 'Switch to 3D Surface')

    # ------------------------------------------------------------------
    # UI signal handlers
    # ------------------------------------------------------------------
    def _on_display_changed(self, idx):
        self._display_mode = ('delta', 'z', 'raw')[idx]

    def _on_baseline_mode_changed(self, idx):
        self._baseline_mode = ('static', 'rolling', 'nominal')[idx]

    def _on_freeze_toggled(self, checked):
        self._freeze = checked
        self.pb_freeze.setStyleSheet(self.MY_YELLOW if checked else '')

    def _on_autoscale_toggled(self, checked):
        self._autoscale = checked
        self.sp_range.setEnabled(not checked)

    def _on_range_changed(self, val):
        self._manual_range = val

    def _on_rolling_t_changed(self, val):
        self._rolling_T = val

    def _on_mouse_move(self, pos):
        if self.plot.sceneBoundingRect().contains(pos):
            vp = self.plot.vb.mapSceneToView(pos)
            cx, cy = int(vp.x()), int(vp.y())
            if 0 <= cx < N_CELLS and 0 <= cy < N_BANDS:
                delay_us = BANDS_META[cy][2][cx]
                self.statusBar().showMessage(
                    'Band {0} ({1}) | Cell {2} ({3}) | delay = {4:.2f} µs'.format(
                        cy, BAND_LABELS[cy], cx, CELL_LABELS[cx], delay_us))
                return
        self._update_status()

    def _update_status(self):
        self.statusBar().showMessage(
            'Frames: {0}  Cmd: {1:<6}  Last: {2}'.format(
                self._frame_count, self._last_cmd, self._last_packet[:60]))

    # ------------------------------------------------------------------
    # Close
    # ------------------------------------------------------------------
    def closeEvent(self, event):
        if self.serial.isOpen():
            self.send_command('E')
            self.serial.waitForBytesWritten(100)
            self.serial.close()
        super().closeEvent(event)


if __name__ == '__main__':
    app = QApplication([])
    window = MainWindow()
    window.resize(1100, 900)
    window.show()
    sys.exit(app.exec())
